# Service — точка доступа для внутренних клиентов
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: web-stack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web
  ports:
    - name: http
      port: 80           # Внутрикластерный порт сервиса
      targetPort: 8080   # Порт контейнера приложения